### ISSUE TITLE
NDoCH planning checklist

### ISSUE THREAD

**Issue by bradweikel** [codeforabq/codeforabq.github.io#7]
### May 9-13
- [x] Brad: Choose a venue
- [x] Post event to Facebook
- [x] Post event to Meetup.com
- [x] Start recruiting volunteers (welcome table (Zach), showcase manager (CivNet rep?), social media, community input station (Lizzie?), Dev table (brad), Map table (Melo).
- [x] Melo: Email everybody from #8 to spread the word
### May 16-20

~~Brad: Make a swag list~~
- [x] Brad: Lock down fatpipe by Thursday afternoon, or book Epicenter 9-12

~~Brad: Flyer~~
- [x] Brad: Post to Code for America's event page
- [x] Brad: Update Brightkite, Facebook & Meetup to reflect venue and revised agenda
### May 23-27
- [x] If needed, print materials
- [x] Brad: hang flyers at tech locations
- [x] Poll attendees about skills/interests
### May 30-June 4 (Week of!)

~~Melo: hang flyers at CNM, co-op, coffee shops, etc~~
- [ ] Melo: Get envelopes/postage
- [ ] Melo: Print memory maps
- [x] Melo: Finish Emailing everybody from #8 to spread the word
- [ ] Lizzie: Focus ImagineABQ station with i-teams
- [ ] Brad: Spitshine agenda for the day based on RSVPs
- [x] Melo: Get coffee from flying star
- [x] Brad: Get bagels and fruit
- [x] Melo: Make sure Zach or Alonso is able to be on site at 8:00 (it'll be zach)

**Comment by bradweikel** [comment]
And a handy timeline spreadsheet:
https://docs.google.com/spreadsheets/d/1hZtzfeFeW_6uW4HsRKAReEGV6u3XyP8LpokEkJAeKMk/edit?ts=570591b0#gid=0

**Comment by bradweikel** [comment]
Just noting another venue idea:

The Peace and Justice Center's hall is dirt cheap. Like $40? It appears to be available June 4. And it's basically an open hall that can seat 150, which is a good size for us... if we break it up into sections, it'll feel fine with 10-50 people roaming around. Not convenient to downtown, but Nob Hill gets lots of foot traffic in its own right, and there might be other events there we could canvas. They probably don't have amazing Wifi, though -- definitely need to check that.
